version: '3.4'

services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management-alpine
    ports: 
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: "exit 0"
    networks:
      - imgproc_net

  imgproc:
    build: 
      context: .
    ports:
      - 9001:9001
    environment:
      - AMQP_HOSTNAME=rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: always
    networks:
      - imgproc_net

networks:
  imgproc_net:
    driver: bridge
