version: '3.4'

services:
  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:3-management-alpine
    ports: 
      - 5672:5672
      - 15672:15672
    healthcheck:
      test: "exit 0"
    network_mode: host

  imgproc:
    build: 
      context: .
    ports:
      - 9001:9001
    # command: './imgproc'
    depends_on:
      rabbitmq:
        condition: service_healthy
    network_mode: host
    restart: always
